# Generated by Django 4.1.7 on 2023-10-16 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_feedback_delete_streamelement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='timestamp',
            new_name='submitted_at',
        ),
    ]
